import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import AppThemeProvider from "./providers/ThemeProvider";
import Navbar from "@/components/navbar/Navbar";
import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v16-appRouter';
import { ThemeProvider } from "@mui/material/styles";
import { getTheme } from "@/theme/theme";
import CssBaseline from "@mui/material/CssBaseline";
import Footer from "@/components/footer/Footer";
import AuthLoader from "@/components/authLoader/AuthLoader";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* mui needs to change the attribute data-light, data-dark */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <InitColorSchemeScript attribute="data" />
        {/* It prevents dark/light mode flicker during page load. */}


        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          {/* mui needs to be wrapped in AppRouterCacheProvider for the color scheme to work so that it can match colors on the server and client */}
          <ThemeProvider theme={getTheme}>
            <CssBaseline enableColorScheme />

            <AuthLoader />
            <Navbar />
            {children}
            <Footer/>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
